In [1]:
%matplotlib inline
import matplotlib.pyplot as plt

# 2.1. Numpy ndarray - создание

Numpy - библиотека для векторизованных вычислений в Python'e. Написана на C. Основной объект в numpy - nddarray, который располагается напрерывно в памяти и позволяет производить быстрые вычисления.

In [4]:
import numpy as np

In [13]:
%%timeit
a = [i ** 2 for i in list(range(10000))]

2.55 ms ± 19.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
a = np.arange(10000)

In [11]:
a ** 2

array([       0,        1,        4, ..., 99940009, 99960004, 99980001])

In [2]:
%%timeit
a = np.array(list(range(10000)))
a * a

858 µs ± 8.99 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%%timeit
a = np.array(list(range(10000)))
a ** 2

854 µs ± 7.61 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%%timeit
a = np.arange(10000)
a ** 2

14.6 µs ± 66 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
np.array([10])

array([10])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Создание массива

In [16]:
a = np.array([1, 2, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a.shape

(4,)

Shape - кортеж, который указывает число элементов в каждом измерении. 

In [24]:
a = np.array([[[1, 2], [3, 4]], 
             [[12, 23], [34, 4]],
              [[2, 21], [54, 44]] ])

In [25]:
a.shape

(3, 2, 2)

In [21]:
a = np.array([1, 2, 3])

In [22]:
a

array([1, 2, 3])

In [23]:
np.arange(start=10, stop=-1, step=-2)

array([10,  8,  6,  4,  2,  0])

In [27]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 23],
        [34,  4]],

       [[ 2, 21],
        [54, 44]]])

In [29]:
a.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4, 12, 23]],

       [[34,  4,  2],
        [21, 54, 44]]])

In [30]:
a.shape

(3, 2, 2)

In [31]:
a.dtype

dtype('int64')

In [32]:
a.itemsize

8

In [33]:
a.nbytes

96

In [36]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 23],
        [34,  4]],

       [[ 2, 21],
        [54, 44]]])

In [41]:
a.reshape(2, -1)

array([[ 1,  2,  3,  4, 12, 23],
       [34,  4,  2, 21, 54, 44]])

In [42]:
a.reshape(1, 3)

ValueError: cannot reshape array of size 12 into shape (1,3)

In [44]:
a.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4, 12, 23],
       [34,  4,  2],
       [21, 54, 44]])

In [45]:
a.reshape(1, -1)

array([[ 1,  2,  3,  4, 12, 23, 34,  4,  2, 21, 54, 44]])

In [46]:
a.reshape(1, -1).shape

(1, 12)

In [47]:
a.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [12],
       [23],
       [34],
       [ 4],
       [ 2],
       [21],
       [54],
       [44]])

При желании, можно использовать np.size(np.object) и np.shape(np.object):

In [48]:
np.size(a)

12

In [49]:
np.shape(a)

(3, 2, 2)

In [50]:
a.size

12

In [51]:
a.shape

(3, 2, 2)

При необходимости, не стоит принебрегать встроенной справкой:

Shift + tab*(1, 2, 4)

In [ ]:
np.array()

И специальными функциями numpy:

In [52]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 23],
        [34,  4]],

       [[ 2, 21],
        [54, 44]]])

In [53]:
np.zeros_like(a)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [54]:
np.lookfor('create array of zeros')

Search results for 'create array of zeros'
------------------------------------------
numpy.zeros_like
    Return an array of zeros with the same shape and type as a given array.
numpy.array
    Create an array.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.ones_like
    Return an array of ones with the same shape and type as a given array.
numpy.diag_indices
    Return the indices to access the main diagonal of an array.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.pad
    Pad an array.
numpy.nditer
    Efficient multi-dimensional iterator object to iterate over arrays.
numpy.full_like
    Return a full array with the same shape and type as a given array.
numpy.empty_like
    Return a new array with the same shape and type as a given array.
numpy.left_shift
    Shift the bits of an integer to the left.
numpy.fft.ifft
    Compute the one-dimensional inverse discrete Fourier Transform.
numpy.fft.ifftn
    Compute the N-dimensional invers

и IPython:

In [5]:
np.ar*?

In [56]:
a = np.array([[1, 2], [3, 4]])

In [57]:
a[0, 0] = 100

In [58]:
a

array([[100,   2],
       [  3,   4]])

**Создание массивов**

Создавать из списков мы уже умеем:

In [59]:
x = [1, 2, 3, 4]

In [60]:
np.array([1, 2, 3, 4], dtype=str)

array(['1', '2', '3', '4'], dtype='<U1')

In [61]:
np.arange(100, 1000, 30)

array([100, 130, 160, 190, 220, 250, 280, 310, 340, 370, 400, 430, 460,
       490, 520, 550, 580, 610, 640, 670, 700, 730, 760, 790, 820, 850,
       880, 910, 940, 970])

In [62]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [63]:
np.linspace(0, 1, 25, endpoint=False)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [64]:
np.linspace(0, 1, 26)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  ])

In [65]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.ones(3)

array([1., 1., 1.])

In [69]:
np.zeros((3, 2, 4, 5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [70]:
np.ones((3, 2), 'complex')

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [71]:
A = np.arange(100).reshape(4, 25)

In [72]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
np.ones_like(A)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

In [74]:
np.zeros_like(A)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [75]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

** Случайные массивы **

на интервале [0,1]:

In [76]:
np.random.rand(3, 2)

array([[0.50755507, 0.0211933 ],
       [0.43352176, 0.44631306],
       [0.23881999, 0.83024573]])

Нормально распределенные:

In [77]:
np.random.randn(3, 2)

array([[ 0.53942869,  1.52676162],
       [-3.2771929 , -1.84856065],
       [ 0.67212494, -1.49297925]])

-- N: иногда полезно получить случайное целое число:

In [78]:
np.random.randint(0, 100, (3, 4))

array([[68, 83, 20, 65],
       [56, 54, 40,  7],
       [17, 79, 43, 45]])

In [80]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
A[-1]

array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

In [82]:
A = np.arange(5)

In [83]:
A

array([0, 1, 2, 3, 4])

In [84]:
A[[0, 1, -4]]

array([0, 1, 1])

# 2.2. Numpy ndarray - индексы

Отдельно рассмотрим 1-мерный и многомерные массивы.

In [89]:
t = np.random.rand(3,)

In [90]:
t

array([0.01220009, 0.45699848, 0.93175194])

Для одномерного массива получим сразу элемент, который находится по данному индексу. Для n-мерного массива подобная индексация вернет массив размера n-1.

In [91]:
t.shape

(3,)

In [92]:
t = np.random.rand(3, 5, 10)
t

array([[[0.84602469, 0.47332988, 0.90255503, 0.22599553, 0.30415374,
         0.71499388, 0.72409148, 0.01867644, 0.2858131 , 0.58048634],
        [0.93078663, 0.3389969 , 0.12008312, 0.51627271, 0.69920706,
         0.29864068, 0.86160962, 0.9058072 , 0.76858325, 0.26123164],
        [0.9384556 , 0.93864246, 0.74504455, 0.91073504, 0.23722471,
         0.49496735, 0.80987834, 0.95456578, 0.63748325, 0.91084975],
        [0.69213675, 0.04294299, 0.8335869 , 0.36994852, 0.936557  ,
         0.48305288, 0.12533161, 0.96445418, 0.01702583, 0.67657077],
        [0.14043997, 0.15531285, 0.64955775, 0.98165422, 0.69480742,
         0.76197389, 0.42520918, 0.13889344, 0.2161863 , 0.76470027]],

       [[0.05460587, 0.49012299, 0.18069018, 0.63092485, 0.55124203,
         0.56708121, 0.81834498, 0.9389873 , 0.19290141, 0.71284402],
        [0.6979398 , 0.2582965 , 0.91580782, 0.53235819, 0.55796442,
         0.32277227, 0.33863078, 0.33230155, 0.97881821, 0.2032152 ],
        [0.66702606, 0.57

In [93]:
t.shape

(3, 5, 10)

In [94]:
t[0, 1, :]

array([0.93078663, 0.3389969 , 0.12008312, 0.51627271, 0.69920706,
       0.29864068, 0.86160962, 0.9058072 , 0.76858325, 0.26123164])

In [95]:
t[0, 1, 5]

0.2986406770764749

In [100]:
t[1][0].shape

(10,)

In [ ]:
np.random.rand(3, 5)[1].shape

Можно использовать ':' вместо индекса:

In [116]:
A = np.random.rand(3, 5)

In [104]:
A

array([[0.92498038, 0.52913164, 0.97118573, 0.54725276, 0.00643798],
       [0.47277675, 0.52208808, 0.15220891, 0.65423408, 0.13044363],
       [0.45414887, 0.98236145, 0.13251409, 0.06027892, 0.06787228]])

In [105]:
A[:, 2]

array([0.97118573, 0.15220891, 0.13251409])

In [106]:
A[0, :]

array([0.92498038, 0.52913164, 0.97118573, 0.54725276, 0.00643798])

In [107]:
A[:, 0]

array([0.92498038, 0.47277675, 0.45414887])

Поддерживается стандартный протокол - python slicing syntax ([lower:upper:step]) :

In [109]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [110]:
A = np.arange(10)

In [111]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
A[0:10:2]

array([[0.09614605, 0.81934237, 0.6296065 , 0.78363101, 0.0771354 ],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

In [119]:
A

array([[0.09614605, 0.81934237, 0.6296065 , 0.78363101, 0.0771354 ],
       [0.97199831, 0.88283356, 0.63043313, 0.92907309, 0.39812661],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

In [121]:
A[0, :][0:5:2]

array([0.09614605, 0.6296065 , 0.0771354 ])

In [122]:
a = A[0, :]

In [123]:
a

array([0.09614605, 0.81934237, 0.6296065 , 0.78363101, 0.0771354 ])

Операция slicing создает т.н. view - то есть данные не копируются, поэтому исходный объект по адресу - mutable.

In [124]:
A[0,:][0:4:2]

array([0.09614605, 0.6296065 ])

In [125]:
A

array([[0.09614605, 0.81934237, 0.6296065 , 0.78363101, 0.0771354 ],
       [0.97199831, 0.88283356, 0.63043313, 0.92907309, 0.39812661],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

In [126]:
A[0,:][0:4:2]

array([0.09614605, 0.6296065 ])

In [127]:
A[0,:][0:4:2] = [2.0, 3.]

In [128]:
A

array([[2.        , 0.81934237, 3.        , 0.78363101, 0.0771354 ],
       [0.97199831, 0.88283356, 0.63043313, 0.92907309, 0.39812661],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

Параметры для slicing могут пропускаться:

In [129]:
A

array([[2.        , 0.81934237, 3.        , 0.78363101, 0.0771354 ],
       [0.97199831, 0.88283356, 0.63043313, 0.92907309, 0.39812661],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

In [130]:
A[0, :][0:4:2]

array([2., 3.])

In [131]:
A[0, :][0:4:]

array([2.        , 0.81934237, 3.        , 0.78363101])

In [132]:
A[0, :][0:3]

array([2.        , 0.81934237, 3.        ])

In [133]:
A[0, :][2:5]

array([3.        , 0.78363101, 0.0771354 ])

In [134]:
A[0, :]

array([2.        , 0.81934237, 3.        , 0.78363101, 0.0771354 ])

In [135]:
A

array([[2.        , 0.81934237, 3.        , 0.78363101, 0.0771354 ],
       [0.97199831, 0.88283356, 0.63043313, 0.92907309, 0.39812661],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

In [137]:
A[::-1, ::-1]

array([[0.49573171, 0.67669995, 0.28159658, 0.68580323, 0.4889261 ],
       [0.39812661, 0.92907309, 0.63043313, 0.88283356, 0.97199831],
       [0.0771354 , 0.78363101, 3.        , 0.81934237, 2.        ]])

In [138]:
A[0, :]

array([2.        , 0.81934237, 3.        , 0.78363101, 0.0771354 ])

In [139]:
A[0, :][:-3]

array([2.        , 0.81934237])

In [140]:
A[0, :][-3:]

array([3.        , 0.78363101, 0.0771354 ])

** Fancy Indexing **

Этим термином обозначается индексирование с помощью массивов (или иных итерируемых конструкций).

In [142]:
A

array([[2.        , 0.81934237, 3.        , 0.78363101, 0.0771354 ],
       [0.97199831, 0.88283356, 0.63043313, 0.92907309, 0.39812661],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

In [146]:
#row_indices = [1, 2]
A[[1, 2]]

array([[0.97199831, 0.88283356, 0.63043313, 0.92907309, 0.39812661],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

In [147]:
col_indices = [1, -1] # [1, 4]
A[row_indices, col_indices]

array([0.88283356, 0.49573171])

Возможно Булево индексирование (**Boolean indexing**):

In [152]:
B = np.array([n for n in range(5)]) ** 2
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 4])

In [150]:
B

array([ 0,  1,  4,  9, 16])

In [154]:
B[B > 2]

array([ 4,  9, 16])

In [157]:
B[(B <= 0) | (B > 2)]

array([ 0,  4,  9, 16])

In [158]:
np.array([1, 0, 1, 0, 0], dtype=bool)

array([ True, False,  True, False, False])

In [159]:
row_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
B[row_mask]

array([0, 4])

In [160]:
row_mask

array([ True, False,  True, False, False])

In [162]:
B

array([ 0,  1,  4,  9, 16])

In [163]:
row_mask = np.array([1, 0, 1, 0, 3])
B[row_mask]

array([1, 0, 1, 0, 9])

Это очень удобно, как вы наверняка догадались, если мы хотим отобрать данные, отвечающие определенным условиям:

In [164]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [165]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [166]:
mask = (5 < x) & (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [167]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [169]:
a = np.array([[1, 2], [3, 4], [4, 5]])

In [170]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [171]:
(a > 1)

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [173]:

a > 2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [172]:
a[a > 2]

array([3, 4, 4, 5])

Получить список индексов элементов, отвечающих заданной маске, можно с помощью **where**:

In [174]:
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [175]:
indices = np.where(mask == True)

indices

(array([11, 12, 13, 14]),)

In [184]:
A

array([[2.        , 0.81934237, 3.        , 0.78363101, 0.0771354 ],
       [0.97199831, 0.88283356, 0.63043313, 0.92907309, 0.39812661],
       [0.4889261 , 0.68580323, 0.28159658, 0.67669995, 0.49573171]])

In [185]:
A[(A < 1) | (A > 2)]

array([0.81934237, 3.        , 0.78363101, 0.0771354 , 0.97199831,
       0.88283356, 0.63043313, 0.92907309, 0.39812661, 0.4889261 ,
       0.68580323, 0.28159658, 0.67669995, 0.49573171])

In [182]:
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [176]:
x[np.where(mask == True)]

array([5.5, 6. , 6.5, 7. ])

**take** еще одна конструкция выбора элементов массива:

In [178]:
v = np.arange(-3, 3)
row_indices = [1, 3, 5]

In [179]:
v

array([-3, -2, -1,  0,  1,  2])

In [180]:
v[row_indices]

array([-2,  0,  2])

In [181]:
v.take(row_indices)

array([-2,  0,  2])

In [ ]:
np.take(v, row_indices)

## TLDR:
* для доступа к элементам массива пользуйтесь slicing и помните, что slicing создает view, а значит исходный массив может быть изменен.

# 2.3. Numpy ndarray - элементарные операции с массивами

** Broadcasting **

Концепеция broadcasting является ключевой для понимания операций с массивами. Обычно, операции с массивами производятся поэлементно. 

In [202]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [203]:
a / b

array([0.5, 1. , 1.5])

Что, если массивы разного размера? Начнем с простого - скаляр и вектор:

In [189]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

** Операции вида "массив - скаляр" **

In [192]:
A * 2

array([[4.        , 1.63868475, 6.        , 1.56726201, 0.15427081],
       [1.94399662, 1.76566713, 1.26086626, 1.85814618, 0.79625321],
       [0.97785219, 1.37160647, 0.56319316, 1.35339991, 0.99146343]])

In [195]:
np.eye(3) * 2

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [196]:
np.ones_like(A) * 2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [197]:
A + np.ones_like(A) * 2

array([[4.        , 2.81934237, 5.        , 2.78363101, 2.0771354 ],
       [2.97199831, 2.88283356, 2.63043313, 2.92907309, 2.39812661],
       [2.4889261 , 2.68580323, 2.28159658, 2.67669995, 2.49573171]])

** Операции вида "массив - массив" **

Производятся поэлементно с учетом правил broadcasting:

In [198]:
A * A

array([[4.00000000e+00, 6.71321927e-01, 9.00000000e+00, 6.14077552e-01,
        5.94987036e-03],
       [9.44780716e-01, 7.79395100e-01, 3.97445930e-01, 8.63176804e-01,
        1.58504794e-01],
       [2.39048728e-01, 4.70326076e-01, 7.92966338e-02, 4.57922828e-01,
        2.45749931e-01]])

In [199]:
A / A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

** Матричные операции**

In [204]:
A = np.random.rand(3, 3)

In [205]:
A

array([[0.79114198, 0.21883353, 0.74619584],
       [0.45411105, 0.40826233, 0.92264349],
       [0.15072064, 0.13098285, 0.38189008]])

In [211]:
A.shape

(3, 3)

In [214]:
b.reshape(3, 1).shape

(3, 1)

In [215]:
np.dot(A, b.reshape(3, 1))

array([[3.5123427 ],
       [3.57003372],
       [1.32718714]])

In [ ]:
A.dot(A)

In [217]:
v = np.random.randn(3)

In [218]:
v

array([-0.28836318, -0.2197935 ,  0.20024796])

In [219]:
v.shape

(3,)

In [220]:
A = np.arange(9).reshape(-3, 3)

In [221]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [222]:
v = np.arange(3)

In [223]:
v

array([0, 1, 2])

In [224]:
v[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [226]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [227]:
v

array([0, 1, 2])

In [225]:
A * v

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [228]:
A * v[:, np.newaxis]

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16]])

In [229]:
np.dot(A, v[:, np.newaxis])

array([[ 5],
       [14],
       [23]])

In [230]:
np.dot(A, v)

array([ 5, 14, 23])

In [232]:
v[:, np.newaxis].shape

(3, 1)

In [233]:
np.dot(A, v[:, np.newaxis])

array([[ 5],
       [14],
       [23]])

In [234]:
A.dot(v[:, np.newaxis])

array([[ 5],
       [14],
       [23]])

In [235]:
np.dot(v[np.newaxis, :], A)

array([[15, 18, 21]])

In [236]:
v

array([0, 1, 2])

In [237]:
np.dot(v, v)

5

Если хочется использовать по умолчанию операции из матричной алгебры, то можно использовать конструктор matrix().

In [238]:
M = np.matrix(A)

In [239]:
M

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [240]:
v1 = np.matrix(v).T

In [241]:
M.shape

(3, 3)

In [242]:
v1

matrix([[0],
        [1],
        [2]])

In [243]:
v1.T * v1

matrix([[5]])

In [244]:
M * v1

matrix([[ 5],
        [14],
        [23]])

** Преобразование массивов**

In [245]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [246]:
A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

** reshape **

In [249]:
a = np.array([1, 2, 3, 4])

In [250]:
a = a.reshape((2, 2))

In [251]:
a

array([[1, 2],
       [3, 4]])

In [252]:
a.reshape(-1, 2)

array([[1, 2],
       [3, 4]])

** concatenate **

In [253]:
a = np.array([[1, 3]])

In [254]:
b = np.array([[5, 6]])

In [255]:
np.concatenate((a, b))

array([[1, 3],
       [5, 6]])

In [257]:
b

array([[5, 6]])

In [258]:
b.T

array([[5],
       [6]])

In [ ]:
a

In [ ]:
b

In [259]:
np.concatenate((a, b), axis=0)

array([[1, 3],
       [5, 6]])

In [260]:
np.concatenate((a, b), axis=1)

array([[1, 3, 5, 6]])

** hstack **

Название говорит само за себя - horizontal stack.

In [261]:
a = np.array([[1], [3]])

In [262]:
a

array([[1],
       [3]])

In [263]:
b.T

array([[5],
       [6]])

In [264]:
np.hstack((a, b.T))

array([[1, 5],
       [3, 6]])

In [265]:
a.shape

(2, 1)

In [266]:
b.T.shape

(2, 1)

** vstack **

In [267]:
a = np.array([2, 3])
b = np.array([4, 5])

In [268]:
np.vstack((a, b))

array([[2, 3],
       [4, 5]])

In [269]:
np.hstack((a, b))

array([2, 3, 4, 5])

In [270]:
a.shape

(2,)

In [271]:
b.shape

(2,)

** Копии и view **

Мы помним, что очень важно различать копирование объекта и присваивание новой ссылки на объект. Numpy в этом смысле не отличается от списков:

In [272]:
A = np.array([[1, 2], [3, 4]])

In [273]:
A

array([[1, 2],
       [3, 4]])

In [274]:
B = A

In [275]:
B[0, 0] = 10

In [276]:
A

array([[10,  2],
       [ 3,  4]])

Если это не тот тип поведения, который нам нужен - следует использовать np.copy():

In [278]:
A = np.array([[1, 2], [3, 4]])

In [279]:
B = np.copy(A)

In [280]:
B[0, 0] = 100

In [282]:
B

array([[100,   2],
       [  3,   4]])

In [281]:
A

array([[1, 2],
       [3, 4]])

Важно помнить, что если вы используете view массива, то копии вы не создаете!

In [283]:
a = np.arange(10)

In [284]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [285]:
b = a[::2]

In [286]:
b

array([0, 2, 4, 6, 8])

In [287]:
np.may_share_memory(a, b)

True

In [288]:
c = a[::2].copy()
np.may_share_memory(a, c)

False

In [290]:
d = np.copy(a.T)
np.may_share_memory(a, d)

False

In [291]:
d[2] = 1000

In [292]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [293]:
b[0] = -11

In [294]:
a

array([-11,   1,   2,   3,   4,   5,   6,   7,   8,   9])

## TLDR:
* следует отличать копию массива и view;
* при осуществлении операций помните про правила broadcasting;
* запомните hstack и vstack.

# 2.4. Numpy - основные функции.

** Встроенные функции массива **

In [295]:
m = np.random.randint(0, 10, (3, 3))

In [299]:
m[np.eye(3)]

IndexError: arrays used as indices must be of integer (or boolean) type

In [298]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [303]:
m * np.eye(3)

array([[4., 0., 0.],
       [0., 3., 0.],
       [0., 0., 9.]])

In [306]:
np.diag(m[np.eye(3, dtype="bool")])

array([[4, 0, 0],
       [0, 3, 0],
       [0, 0, 9]])

In [300]:
m[np.eye(3, dtype=bool)].sum()

16

In [309]:
np.max(m)

9

In [307]:
m.max()

9

In [308]:
m.min()

0

** Всегда используйте встроенные функции! **

In [311]:
a = np.random.rand(1000)

In [312]:
%timeit -n 1000 max(a)

96 µs ± 5.01 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [313]:
%timeit -n 1000 a.max()

The slowest run took 55.74 times longer than the fastest. This could mean that an intermediate result is being cached.
26.2 µs ± 55.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [314]:
%timeit -n 1000 sum(a)

154 µs ± 627 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [321]:
%timeit -n 1000 a.sum()

5.43 µs ± 1.45 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [320]:
%timeit -n 1000 np.sum(a)

6.64 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Просто считать сумму элементов матрицы или находить максимальный элемент не так интересно, и тут нам помогают axis:

In [316]:
np.sum(m)

array([[4, 0, 7],
       [3, 3, 4],
       [6, 1, 9]])

In [322]:
m.sum(axis=0)

array([13,  4, 20])

In [323]:
m.sum(axis=1)

array([11, 10, 16])

In [325]:
m.max(axis=0)

array([6, 3, 9])

Очень полезно произведение всех элементов:

In [328]:
m

array([[4, 0, 7],
       [3, 3, 4],
       [6, 1, 9]])

In [329]:
m.prod(axis=1)

array([ 0, 36, 54])

In [331]:
m

array([[4, 0, 7],
       [3, 3, 4],
       [6, 1, 9]])

In [333]:
np.hstack((m, m))

array([[4, 0, 7, 4, 0, 7],
       [3, 3, 4, 3, 3, 4],
       [6, 1, 9, 6, 1, 9]])

In [332]:
np.concatenate((m, m), axis=1)

array([[4, 0, 7, 4, 0, 7],
       [3, 3, 4, 3, 3, 4],
       [6, 1, 9, 6, 1, 9]])

In [335]:
m.prod()

0

Кумулятивная сумма элементов:

In [339]:
m

array([[4, 0, 7],
       [3, 3, 4],
       [6, 1, 9]])

In [338]:
m.ravel()

array([4, 0, 7, 3, 3, 4, 6, 1, 9])

In [337]:
m.cumsum()

array([ 4,  4, 11, 14, 17, 21, 27, 28, 37])

Кумулятивное произведение:

In [344]:
m[0, 1] = 1

In [345]:
m

array([[1, 1, 7],
       [3, 3, 4],
       [6, 1, 9]])

In [346]:
m.cumprod()

array([    1,     1,     7,    21,    63,   252,  1512,  1512, 13608])

**Простые статистики**

**Среднее**

In [348]:
m

array([[1, 1, 7],
       [3, 3, 4],
       [6, 1, 9]])

In [349]:
m.mean(axis=0)

array([3.33333333, 1.66666667, 6.66666667])

In [350]:
np.mean(m, axis=1)

array([3.        , 3.33333333, 5.33333333])

In [351]:
np.mean(m)

3.888888888888889

In [352]:
m.mean(axis=0)

array([3.33333333, 1.66666667, 6.66666667])

**Медиана**

In [353]:
np.median(m, axis=0)

array([3., 1., 7.])

In [354]:
np.median(m)

3.0

** Дисперсия **

In [355]:
np.std(m, axis=0)

array([2.05480467, 0.94280904, 2.05480467])

In [356]:
m.std(axis=0)

array([2.05480467, 0.94280904, 2.05480467])

In [357]:
np.var(a)

0.08300465050945464

In [358]:
a.var()

0.08300465050945464

** Сортировка **

In [6]:
a = np.random.randint(0, 100, 12)

In [7]:
a

array([37, 34, 60, 37, 67, 57,  3, 35, 12, 41, 70, 88])

In [8]:
sorted(a, reverse=True)

[88, 70, 67, 60, 57, 41, 37, 37, 35, 34, 12, 3]

In [10]:
a

array([37, 34, 60, 37, 67, 57,  3, 35, 12, 41, 70, 88])

In [11]:
np.sort(a)[::-1]

array([88, 70, 67, 60, 57, 41, 37, 37, 35, 34, 12,  3])

Функция выше возвращает отсортированную копию массива. Если нужна сортировка in-place:

In [361]:
a = np.random.randint(0, 100, 12)

In [362]:
a

array([74, 40, 69, 26, 90, 91, 50,  2, 50, 49, 54, 30])

In [363]:
a = np.sort(a)

array([ 2, 26, 30, 40, 49, 50, 50, 54, 69, 74, 90, 91])

In [364]:
a

array([74, 40, 69, 26, 90, 91, 50,  2, 50, 49, 54, 30])

In [366]:
a = np.random.randint(0, 100, 12)

In [367]:
a

array([65,  6, 40, 81, 13, 29,  9, 52, 68, 95, 64, 46])

In [368]:
np.sort(a)

array([ 6,  9, 13, 29, 40, 46, 52, 64, 65, 68, 81, 95])

In [369]:
a

array([65,  6, 40, 81, 13, 29,  9, 52, 68, 95, 64, 46])

In [370]:
a.sort()

In [371]:
a

array([ 6,  9, 13, 29, 40, 46, 52, 64, 65, 68, 81, 95])

In [372]:
a = np.random.rand(100)

In [373]:
a = np.random.randint(0, 100, 120)

In [374]:
a

array([98, 80, 91, 35, 89, 80, 12, 48, 14, 60, 92,  9,  1, 15, 52, 47, 97,
       92, 57, 83, 73, 32, 44, 44, 32, 68, 48, 96, 14, 37, 69, 23, 52, 91,
       85, 51, 67, 80, 73, 91, 33, 52, 70, 52, 54, 62, 75, 24, 84, 63, 68,
       17, 14, 77, 89, 57, 65, 12, 65, 83, 16, 18,  7, 59, 25, 34, 22, 28,
       67, 93, 48, 61, 16, 83, 92, 63, 75, 13, 21, 54, 51, 25, 80, 73, 62,
       50, 84,  9, 44, 29, 89, 94, 31, 52, 66,  5, 49, 63, 12, 70, 59, 71,
       34, 32,  3,  7, 82, 71, 70, 41, 24, 95, 79, 14, 75, 94, 84, 31, 57,
       66])

Также иногда бывает полезно получить только список индексов в правильном порядке:

In [375]:
a = np.random.randint(0, 10, 10)

In [376]:
a

array([7, 3, 3, 1, 4, 1, 1, 9, 0, 8])

In [377]:
np.argsort(a)

array([8, 3, 5, 6, 1, 2, 4, 0, 9, 7])

In [378]:
a[np.argsort(a)]

array([0, 1, 1, 1, 3, 3, 4, 7, 8, 9])

In [379]:
np.argmax(a)

7

In [380]:
np.argmin(a)

8

In [381]:
a

array([7, 3, 3, 1, 4, 1, 1, 9, 0, 8])

In [382]:
a

array([7, 3, 3, 1, 4, 1, 1, 9, 0, 8])

In [383]:
np.nonzero(a)

(array([0, 1, 2, 3, 4, 5, 6, 7, 9]),)

** Функции для работы с матрицами **

In [384]:
m

array([[1, 1, 7],
       [3, 3, 4],
       [6, 1, 9]])

In [385]:
np.diag(m)

array([1, 3, 9])

In [386]:
m.diagonal()

array([1, 3, 9])

Для целого класса функций из линейной алгебры есть свой суб-модуль np.linalg.

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

** Условные выражения **

Как вы уже поняли, для вектора конструкция типа if (vector) не подходит.

In [413]:
M

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [416]:
i = 0
if (M > i).all():
    print("at least one element in M is larger than {}".format(i))
else:
    print("no element in M is larger than {}".format(i))

no element in M is larger than 0


In [ ]:
if (M > -1).all():
    print("all elements in M are larger than -1")
else:
    print("all elements in M are not larger than -1")

## TLDR:
- всегда используйте встроенные в np функции;
- векторизуйте везде, где это возможно!

# 2.5. Numpy - I/O.

В данном случае у нас на выбор 2 опции - либо формат numpy, либо просто текстовый файл.

In [417]:
!ls

Black_man.txt	 HW1.ipynb	   numpy.ipynb	 random123.npy	random.npy
frame123.csv.gz  matplotlib.ipynb  pandas.ipynb  random.csv	random_txt.csv


In [418]:
np.save("random1234.npy", M)

In [419]:
!ls

Black_man.txt	 matplotlib.ipynb  random1234.npy  random.npy
frame123.csv.gz  numpy.ipynb	   random123.npy   random_txt.csv
HW1.ipynb	 pandas.ipynb	   random.csv


In [420]:
!cat Black_man.txt | head -9

Черный человек
Друг мой, друг мой,
Я очень и очень болен.
Сам не знаю, откуда взялась эта боль.
То ли ветер свистит
Над пустым и безлюдным полем,
То ль, как рощу в сентябрь,
Осыпает мозги алкоголь.



In [421]:
N = np.load("random1234.npy")

In [426]:
np.savetxt('random_txt.csv', M, delimiter='\t', fmt='%.1e')

In [427]:
! cat random_txt.csv

0.0e+00	1.0e+00	2.0e+00
3.0e+00	4.0e+00	5.0e+00
6.0e+00	7.0e+00	8.0e+00


In [428]:
np.loadtxt('random_txt.csv')

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

# А теперь задачки!

#### Написать функцию, которая поможет развернуть все слова в строке:

In [4]:
s = "Hello world"

In [5]:
def reverse(x):
    return x[::-1]

In [6]:
reverse(s)

'dlrow olleH'

#### Написать функцию, которая определяет является ли число палиндромом

In [10]:
x1 = 126567654
x2 = 12345654321

In [11]:
def is_palindrom(x):
    return str(x) == str(x)[::-1]

In [20]:
def is_palindrom(x):
    x_str = str(x)
    flag = 1
    for i in range(len(x_str) // 2):
        if x_str[i] != x_str[-(i+1)]:
            flag = 0
            break
    return bool(flag)

In [21]:
is_palindrom(x1)

False

In [22]:
is_palindrom(x2)

True

#### Сложите цифры целого числа

In [25]:
a = 126567654

In [29]:
import numpy as np

In [31]:
def summarize(a):
    return np.array(list(str(a))).astype(int).sum()

In [449]:
summarize(a)

42

#### Извлеките из массива числа, делимые на 15.

In [34]:
nums = np.array([45, 55, 60, 37, 100, 105, 220])

In [35]:
def dev_15(ar):
    return ar[ar % 15 == 0]

In [36]:
dev_15(nums)

array([ 45,  60, 105])

#### Напишите программу, которая принимает текст и выводит два слова: наиболее часто встречающееся и самое длинное.

In [455]:
with open('./Black_man.txt') as f:
    black = f.readlines()

In [456]:
lower = (" ".join(black).lower())

In [457]:
only_letters = ""
for i in lower:
    if (i >= "а" and i <= "я") or i in [" ", "\n"]:
        only_letters += i

In [458]:
only_letters = only_letters.replace("\n", " ")

In [459]:
x = only_letters.split()

#### Напишите функцию, которая создаёт комбинацию двух списков таким образом:

[1, 2, 3] (+) [11, 22, 33] -> [1, 11, 2, 22, 3, 33]

In [38]:
x = np.array([1, 2, 3, -1])
y = np.array([11, 22, 33, 1123])

In [41]:
def union(a, b):
    ans = []
    for i in zip(a, b):
        ans.extend(i)
    return ans

In [43]:
def union(a, b):
    ans = np.zeros(len(a) + len(b), dtype=int)
    ans[::2] = a
    ans[1::2] = b
    return ans

In [42]:
union(x, y)

[1, 11, 2, 22, 3, 33, -1, 1123]

In [44]:
union(x, y)

array([   1,   11,    2,   22,    3,   33,   -1, 1123])

In [58]:
def union(a, b):
    return np.hstack((a, b))[np.array(list(zip(range(a.shape[0]), range( a.shape[0], a.shape[0] + b.shape[0]))))].ravel()

In [59]:
union(x, y)

array([   1,   11,    2,   22,    3,   33,   -1, 1123])

#### Написать функцию, которая удаляет лишние пробелы в строке

In [62]:
x = " I   Love        Python    "

In [69]:
def delete_spaces(string):
    return " ".join(string.split())

In [ ]:
delete_spaces(x)